sudo: false
language: node_js
node_js:
  - "4"
  - "5"
  - "6"
  - "7"
  - "8"
  - "9"
env:
  - TEST_SUITE=unit
matrix:
  include:
    - node_js: "8"
      env: TEST_SUITE=standard
script: npm run-script $TEST_SUITE
